# Generated by Django 4.1.2 on 2023-07-20 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_tool', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardiacDiseaseRisk',
        ),
    ]
