# Generated by Django 4.1.2 on 2023-07-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_tool', '0003_trainedmodel_delete_traininghistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('accuracy', models.FloatField()),
                ('training_time', models.FloatField()),
                ('train_scale', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='TrainedModel',
        ),
    ]
