# Generated by Django 4.1.2 on 2023-07-21 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_tool', '0004_trainedmodelhistory_delete_trainedmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainedmodelhistory',
            old_name='training_time',
            new_name='timestamp',
        ),
    ]
