# Generated by Django 4.1.2 on 2023-07-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_tool', '0005_rename_training_time_trainedmodelhistory_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedmodelhistory',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
